apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: curl-jq
  name: curl-jq
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     app: curl-jq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curl-jq
    spec:
      containers:
      - image: peterevans/curl-jq
        name: curl-jq
        resources: {}
status: {}
