apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dnsutil
  name: dnsutil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsutil
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dnsutil
    spec:
      containers:
      - image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
        name: jessie-dnsutils
        command:
        - sleep
        - "infinity"
        resources: {}
status: {}
